// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSuD4CTm9ZjLBiKfjp664hQS_isStrvPs',
    appId: '1:808088559452:android:be1d949fcb5fac2c5beb99',
    messagingSenderId: '808088559452',
    projectId: 'rc-firebase-e7c09',
    databaseURL: 'https://rc-firebase-e7c09-default-rtdb.firebaseio.com',
    storageBucket: 'rc-firebase-e7c09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlqwq7hzQof1vFDIgyvcvlWZb_g1FsIec',
    appId: '1:808088559452:ios:e52b27f7cf969e7f5beb99',
    messagingSenderId: '808088559452',
    projectId: 'rc-firebase-e7c09',
    databaseURL: 'https://rc-firebase-e7c09-default-rtdb.firebaseio.com',
    storageBucket: 'rc-firebase-e7c09.firebasestorage.app',
    iosClientId: '808088559452-m2fvcimgpvsvc2lv5rrntrrrcqntm5lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApp',
  );
}
